// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhxegdansdhnboxbkfur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoeGVnZGFuc2RobmJveGJrZnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzc2NjQsImV4cCI6MjA2NDc1MzY2NH0.AHOukD0Ty3MwbSAUV5Yui-CXdNc19vfY8Pu2JgR6g38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);